- name: install packages
  yum:
    name: "{{cockpit_packages}}"
    state: present
  become: yes

- name: start and enable service
  service:
    name: cockpit.socket
    state: started
    enabled: yes
  become: yes