- name: install dependencies
  pip:
    name: "{{os_packages}}"
    state: present
  become: yes

- name: source keystonerc_admin
  lineinfile:
    src: "{{ansible_env.HOME}}/.bashrc"
    regexp: source {{ansible_env.HOME}}/keystonerc_admin