- name: Gather facts about a previously created image
  os_image_facts:
    image: "{{os_image}}"

- name: Gather facts about a previously created network by name
  os_networks_facts:
    name: "{{os_network}}"

- name: Gather facts about a flavor
  os_flavor_facts:
    name: "{{os_flavor}}"

- debug:
    var: openstack_flavors

- name: copy pubkey
  copy:
    src: "{{pubkey}}"
    dest: "{{os_pubkey}}"

- name: create os keypair
  os_keypair:
    state: present
    name: "{{os_pubkey_name}}"
    public_key_file: "{{os_pubkey}}"

- name: launch instance
  os_server:
    state: present
    name: plex-live
    image: "{{openstack_image.id}}"
    key_name: "{{os_pubkey}}"
    nics:
      - net-id: "{{openstack_networks[0].id}}"
    timeout: 200
    flavor: "{{openstack_flavors.id}}"
    meta:
      hostname: plex.magiccityit.com
      group: plex
    wait: yes
    auto_floating_ip: yes
  register: plex

- name: wait for server to deploy
  wait_for:
    host: "{{plex.server.public_v4}}"
    port: 22
    search_regex: OpenSSH
    state: started
    timeout: 300
    delay: 60
  delegate_to: localhost
  when: reboot.changed

- name: Add CentOS Instance to Inventory
  add_host: 
    name: plex.magiccityit.com
    groups: plex
    ansible_ssh_host: "{{ plex.server.public_v4 }}"