- name: Gather facts about a previously created image
  os_image_facts:
    image: "{{os_image}}"

- name: Show image facts
  debug:
    var: openstack_image

- name: Gather facts about a previously created network by name
  os_networks_facts:
    name: "{{os_network}}"

- name: Show network facts
  debug:
    var: openstack_networks

- name: copy pubkey
  copy:
    src: "{{pubkey}}"
    dest: "{{os_pubkey}}"

- name: create os keypair
  os_keypair:
    state: present
    name: "{{os_pubkey_name}}"
    public_key_file: "{{os_pubkey}}"

- name: launch instance
  os_server:
    state: present
    name: plex-live
    image: "{{os_image_info.id}}"
    key_name: "{{os_pubkey}}"
    nics:
      net-id: "{{os_net_info.id}}"
    timeout: 200
    flavor: 6
    meta:
      hostname: plex.magiccityit.com
      group: plex
    wait: yes
    auto_floating_ip: yes
    register: plex

- name: wait for server to deploy
  wait_for:
    host: "{{plex.server.public_v4}}"
    port: 22
    search_regex: OpenSSH
    state: started
    timeout: 300
    delay: 60
  delegate_to: localhost
  when: reboot.changed

- name: Add CentOS Instance to Inventory
  add_host: 
    name: plex.magiccityit.com
    groups: plex
    ansible_ssh_host: "{{ plex.server.public_v4 }}"