- name: check if docker-ce is installed
  yum:
    list: installed
  become: yes
  register: docker_ce

- debug:
    var: docker_ce

- name: remove existing docker packages
  yum:
    name: "{{docker_packages}}"
    state: absent
  become: yes
  when: docker_ce.results[0].find("already installed") == -1

- name: install required docker packages
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
  become: yes

- name: add docker-ce stable repo
  yum_repository:
    name: Docker CE Stable - $basearch
    file: docker-ce
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: add docker-ce stable source repo
  yum_repository:
    name: Docker CE Stable - Sources
    file: docker-ce
    baseurl: https://download.docker.com/linux/centos/7/source/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: install docker ce
  yum:
    name: docker-ce
    state: present
  become: yes

- name: start and enable docker
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: install docker-py
  pip:
    name: docker-py
    state: present
  become: yes