- name: create plex container
  docker_container:
    name: mcit_plex
    image: plexinc/pms-docker:plexpass
    state: started
    exposed_ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    env:
      TZ: America/Chicago
      PLEX_UID: 1001
      PLEX_GID: 1001
      CHANGE_CONFIG_DIR_OWNERSHIP: true
      HOSTNAME: plex-live
      PLEX_CLAIM: "{{claim_token}}"
      ADVERTISE_IP: http://{{hostvars['plex.magiccityit.com']['ansible_default_ipv4']['address']}}:32400/
      ALLOWED_NETWORKS: "{{allowed_nets}}"
    volumes:
      - "{{config}}:/config"
      - "{{transcode}}:/transcode"
      - "{{media}}:/data"
  become: yes
